
version: 2

models:
  - name: users_table
    description: "Users table which stores all the data of the user"
    columns:
      - name: ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: posts_table
    description: "Posts table which stores all the post details of the user"
    columns:
      - name: ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: badges_table
    description: "Badges table which stores all the badge details of the user"
    columns:
      - name: ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null